version: '2'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - thavyra_postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@thavyra.xyz
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - thavyra_pgadmin_data:/var/lib/pgadmin
      
volumes:
  thavyra_postgres_data:
  thavyra_pgadmin_data:
    